# #############################################################################
# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
# #############################################################################
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "app.fullname" . }}-cert-transfer-daps
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: cert-transfer-daps
spec:
  template:
    metadata:
      labels:
        {{- include "app.labels" . | nindent 8 }}
        app.kubernetes.io/component: cert-transfer-daps
    spec:
      containers:
      - name: transfer
        image: ghcr.io/taskmedia/curl-jq:main
        command:
          - /home/curl_user/entrypoint.sh
        # command:
        #   - sleep
        #   - "3600"
        env:
          - name: DAPS_ADDR
            value: {{ tpl .Values.daps.url . }}

          - name: DAPS_AUTH_CLIENT_ID
            value: {{ .Values.daps.auth.clientId | required ".Values.daps.auth.clientId is required" }}

          - name: DAPS_AUTH_CLIENT_SECRET
            value: {{ .Values.daps.auth.clientSecret | required ".Values.daps.auth.clientSecret is required" }}

          - name: DAPS_EDC_CLIENT_ID
            value: {{ .Values.daps.edc.clientId | required ".Values.daps.edc.clientId is required" }}

          - name: DAPS_PUBLICKEY_VALUE
            valueFrom:
              secretKeyRef:
                name: {{ include "app.fullname" . }}-daps
                key: tls.crt

        volumeMounts:
        - name: script
          mountPath: /home/curl_user/entrypoint.sh
          subPath: entrypoint.sh
      volumes:
      - name: script
        configMap:
          name: {{ include "app.fullname" . }}-cert-transfer-daps-script
          defaultMode: 0777
      restartPolicy: Never
  backoffLimit: 5
  # activeDeadlineSeconds: 15
  # ttlSecondsAfterFinished: 3600
  parallelism: 1
