# #############################################################################
# Copyright (c) 2022,2024 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
# Copyright (c) 2021,2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
# #############################################################################
---
apiVersion: v2
name: tx-data-provider
description: A Helm chart for Kubernetes

type: application
version: 0.1.5
appVersion: 0.0.1

dependencies:
  - name: digital-twin-registry
    version: 0.6.3
    repository: https://eclipse-tractusx.github.io/charts/dev
    condition: digital-twin-registry.enabled
  - name: simple-data-backend
    repository: https://eclipse-tractusx.github.io/charts/dev
    version: 0.1.0
    condition: simple-data-backend.enabled
  - name: tractusx-connector
    repository: https://eclipse-tractusx.github.io/charts/dev
    version: 0.8.0
    condition: tractusx-connector.enabled
  - name: vault
    version: 0.20.0
    repository: https://helm.releases.hashicorp.com
    condition: vault.enabled
