# #############################################################################
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
# #############################################################################

digital-twin-registry:
  # @ignore
  enablePostgres: false
  registry:
    # @ignore
    authentication: false
    # -- External hostname for Digital Twin Registry
    # @section -- Registry Configuration
    host: dataprovider-dtr.test
    # FIX PROBLEMS WITH INGRESS AND PATH HANDLING
    ingress:
      # disable urlPrefix behaviour (that appends a regex to the path)
      urlPrefix: ""
      # provide explicit rules so we can set pathType to ImplementationSpecific
      rules:
        - host: dataprovider-dtr.tx.test
          http:
            paths:
              - path: "/semantics/registry(/|$)(.*)"
                pathType: ImplementationSpecific
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "my-ca-issuer"
        nginx.ingress.kubernetes.io/rewrite-target: "/$2"
        nginx.ingress.kubernetes.io/use-regex: "true"

    # === Bring Your Own ===
    dataSource:
      # -- Database connection URL
      # (needs to be set explicitly via --set digital-twin-registry.registry.dataSource.url=jdbc:postgresql://<release-name>-postgresql:5432/dtr)
      # @section -- Registry Database Configuration (Bring Your Own)
      url: "jdbc:postgresql://<release-name>-postgresql:5432/dtr"
      # -- Database username
      # @section -- Registry Database Configuration (Bring Your Own)
      user: "user"
      # -- Database password
      # @section -- Registry Database Configuration (Bring Your Own)
      password: "password"

# PostgreSQL Configuration
postgresql:
  image:
    # -- workaround to use bitnamilegacy chart for version 12.12.x till committers align on new postgresql charts
    repository: bitnamilegacy/postgresql
    # -- workaround to use bitnamilegacy chart for version 12.12.x till committers align on new postgresql charts
    tag: 15.4.0-debian-11-r45
  auth:
    # -- Database username
    # @section -- PostgreSQL Configuration
    username: "user"
    # -- Database password
    # @section -- PostgreSQL Configuration
    password: "password"
    # -- Database name
    # @section -- PostgreSQL Configuration
    database: "dtr"
  primary:
    persistence:
      # -- Enable persistent storage for PostgreSQL
      # @section -- PostgreSQL Configuration
      enabled: true
      # -- Size of persistent volume
      # @section -- PostgreSQL Configuration
      size: "10Gi"
