{{- if and (index .Values "external-secrets" "enabled") .Values.vault.enabled .Values.externalSecrets }}
{{- range $secretName, $kv := .Values.externalSecrets }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $secretName }}
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: {{ $.Values.vault.secretStore.name | default "vault-store" }}
    kind: SecretStore
  target:
    name: {{ $secretName }}
    creationPolicy: Owner
  data:
{{- range $key, $_ := $kv }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ $secretName }}
        property: {{ $key }}
{{- end }}
---
{{- end }}
{{- end }}
