# #############################################################################
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
# #############################################################################

apiVersion: v2
name: identity-and-trust-bundle
description: |
  Helm chart for Capability Bundle: Identity and Trust

  The Identity & Trust Bundle provides identity management and authentication services for the Catena-X ecosystem.

  For more information on the SSI DIM Wallet stub application, see https://github.com/eclipse-tractusx/ssi-dim-wallet-stub

home: https://github.com/eclipse-tractusx/tractus-x-umbrella/tree/main/charts/identity-and-trust-bundle

sources:
  - https://github.com/eclipse-tractusx/tractus-x-umbrella/tree/main/charts/identity-and-trust-bundle

type: application
version: 1.1.2

dependencies:
  - name: ssi-dim-wallet-stub
    version: 0.1.14
    repository: https://eclipse-tractusx.github.io/charts/dev
    condition: ssi-dim-wallet-stub.enabled
